# Generated by Django 5.0.3 on 2024-03-07 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boothName', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneTypeId', models.CharField(blank=True, max_length=255, null=True)),
                ('boothTypeId', models.CharField(blank=True, max_length=255, null=True)),
                ('directoryTypeId', models.CharField(blank=True, max_length=255, null=True)),
                ('directoryTabletSerialNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('physicalAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zipCode', models.IntegerField(blank=True, null=True)),
                ('installationDate', models.CharField(blank=True, max_length=255, null=True)),
                ('installationType', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('isADAAccessible', models.BooleanField(default=False)),
                ('phoneSerialNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('highlightedCriteria', models.CharField(blank=True, max_length=255, null=True)),
                ('installationNotes', models.TextField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('boothMaintainerId', models.UUIDField(blank=True, null=True)),
                ('deviceInfo', models.TextField(blank=True, null=True)),
                ('boothImage', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booth',
            },
        ),
        migrations.CreateModel(
            name='BoothAndPoemCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boothId', models.UUIDField()),
                ('poemCollectionId', models.UUIDField()),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booth_and_poem_collection',
            },
        ),
        migrations.CreateModel(
            name='BoothMaintainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booth_maintainer',
            },
        ),
        migrations.CreateModel(
            name='DirectoryType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'directory_type',
            },
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'era',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('languageId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone_type',
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('poetId', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('audioLink', models.CharField(blank=True, max_length=255, null=True)),
                ('producerName', models.CharField(blank=True, max_length=255, null=True)),
                ('narratorName', models.CharField(blank=True, max_length=255, null=True)),
                ('recordingDate', models.DateTimeField(blank=True, null=True)),
                ('recordingSource', models.CharField(blank=True, max_length=255, null=True)),
                ('poemEra', models.CharField(blank=True, max_length=255, null=True)),
                ('poemTypes', models.TextField(blank=True, null=True)),
                ('poemTopics', models.TextField(blank=True, null=True)),
                ('poemSpecialTags', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('optionalLegal', models.TextField(blank=True, null=True)),
                ('isChildrensPoem', models.BooleanField(default=False)),
                ('isAdultPoem', models.BooleanField(default=False)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('recordingDuration', models.CharField(blank=True, max_length=255, null=True)),
                ('telepoemNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('copyRights', models.CharField(blank=True, max_length=255, null=True)),
                ('poemText', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'poem',
            },
        ),
        migrations.CreateModel(
            name='PoemCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poemCollectionName', models.CharField(blank=True, max_length=255, null=True)),
                ('poemCollectionDescription', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poem_collection',
            },
        ),
        migrations.CreateModel(
            name='PoemCollectionAndPoem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poemCollectionId', models.UUIDField()),
                ('poemId', models.UUIDField()),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poem_collection_and_poem',
            },
        ),
        migrations.CreateModel(
            name='PoemTopic',
            fields=[
                ('poemTopicId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poem_topic',
            },
        ),
        migrations.CreateModel(
            name='PoemType',
            fields=[
                ('poemTypeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poem_type',
            },
        ),
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNum', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('zipCode', models.CharField(blank=True, max_length=255, null=True)),
                ('isLaureate', models.BooleanField(default=False)),
                ('photoCredit', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('legalFirstName', models.CharField(default='anonymous', max_length=255)),
                ('legalLastName', models.CharField(default='anonymous', max_length=255)),
                ('creditedFirstName', models.CharField(default='anonymous', max_length=255)),
                ('creditedLastName', models.CharField(default='anonymous', max_length=255)),
                ('poetImage', models.CharField(blank=True, max_length=255, null=True)),
                ('poetBiography', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'poet',
            },
        ),
        migrations.CreateModel(
            name='PoetAndPoem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poemId', models.UUIDField()),
                ('poetId', models.UUIDField()),
            ],
            options={
                'db_table': 'poet_and_poem',
            },
        ),
        migrations.CreateModel(
            name='SpecialTag',
            fields=[
                ('specialTagId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'special_tag',
            },
        ),
        migrations.CreateModel(
            name='TelepoemBoothType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telepoem_booth_type',
            },
        ),
    ]
