# Generated by Django 5.0.3 on 2024-03-07 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoothMaintainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booth_maintainer',
            },
        ),
        migrations.CreateModel(
            name='DirectoryType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'directory_type',
            },
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'era',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone_type',
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('audioLink', models.CharField(blank=True, max_length=255, null=True)),
                ('producerName', models.CharField(blank=True, max_length=255, null=True)),
                ('narratorName', models.CharField(blank=True, max_length=255, null=True)),
                ('recordingDate', models.DateTimeField(blank=True, null=True)),
                ('recordingSource', models.CharField(blank=True, max_length=255, null=True)),
                ('poemEra', models.CharField(blank=True, max_length=255, null=True)),
                ('poemTypes', models.CharField(blank=True, max_length=255, null=True)),
                ('poemTopics', models.CharField(blank=True, max_length=255, null=True)),
                ('poemSpecialTags', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('optionalLegal', models.TextField(blank=True, null=True)),
                ('isChildrenPoem', models.BooleanField(db_column='isChildrenPoem', default=False)),
                ('isAdultPoem', models.BooleanField(default=False)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('recordingDuration', models.CharField(blank=True, max_length=255, null=True)),
                ('telepoemNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('copyRights', models.CharField(blank=True, max_length=255, null=True)),
                ('poemText', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poem',
            },
        ),
        migrations.CreateModel(
            name='PoemCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poemCollectionName', models.CharField(max_length=255)),
                ('poemCollectionDescription', models.TextField()),
                ('filterExplicitLanguage', models.BooleanField(default=False)),
                ('filterAdultContent', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poem_collection',
            },
        ),
        migrations.CreateModel(
            name='PoemTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poem_topic',
            },
        ),
        migrations.CreateModel(
            name='PoemType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poem_type',
            },
        ),
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNum', models.CharField(blank=True, db_column='phoneNum', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('zipCode', models.CharField(blank=True, db_column='zipCode', max_length=255, null=True)),
                ('isLaureate', models.BooleanField(default=False)),
                ('photoCredit', models.CharField(blank=True, db_column='photoCredit', max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('legalFirstName', models.CharField(default='anonymous', max_length=255)),
                ('legalLastName', models.CharField(default='anonymous', max_length=255)),
                ('creditedFirstName', models.CharField(default='anonymous', max_length=255)),
                ('creditedLastName', models.CharField(default='anonymous', max_length=255)),
                ('poetImage', models.CharField(blank=True, max_length=255, null=True)),
                ('poetBiography', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poet',
            },
        ),
        migrations.CreateModel(
            name='SpecialTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'special_tag',
            },
        ),
        migrations.CreateModel(
            name='TelepoemBoothType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telepoem_booth_type',
            },
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boothName', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneType', models.CharField(blank=True, max_length=255, null=True)),
                ('boothType', models.CharField(blank=True, max_length=255, null=True)),
                ('directoryType', models.CharField(blank=True, max_length=255, null=True)),
                ('directoryTabletSerialNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('physicalAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zipCode', models.IntegerField(blank=True, null=True)),
                ('installationDate', models.CharField(blank=True, max_length=255, null=True)),
                ('installationType', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('isADAAccessible', models.BooleanField(default=False)),
                ('phoneSerialNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('highlightedCriteria', models.CharField(blank=True, max_length=255, null=True)),
                ('installationNotes', models.TextField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('deviceInfo', models.TextField(blank=True, null=True)),
                ('boothImage', models.CharField(blank=True, max_length=255, null=True)),
                ('boothMaintainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.boothmaintainer')),
            ],
            options={
                'db_table': 'booth',
            },
        ),
        migrations.CreateModel(
            name='BoothAndPoemCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booth')),
                ('poemCollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poemcollection')),
            ],
            options={
                'db_table': 'booth_and_poem_collection',
            },
        ),
        migrations.CreateModel(
            name='PoemCollectionAndPoem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deletedAt', models.DateField(blank=True, null=True)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poem')),
                ('poemCollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poemcollection')),
            ],
            options={
                'db_table': 'poem_collection_and_poem',
            },
        ),
        migrations.AddField(
            model_name='poem',
            name='poet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poet'),
        ),
        migrations.CreateModel(
            name='PoetAndPoem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poem')),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poet')),
            ],
            options={
                'db_table': 'poet_and_poem',
            },
        ),
    ]
