# Generated by Django 5.0.3 on 2024-03-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='boothMaintainerId',
        ),
        migrations.AddField(
            model_name='booth',
            name='maintainerEmail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='maintainerName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='maintainerNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
